//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 04:37:41 PM CET 
//


package com.immunization.common.model.izvestaj_o_imunizaciji;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.izvestaj_o_imunizaciji package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.izvestaj_o_imunizaciji
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji }
     * 
     */
    public IzvestajOImunizaciji createIzvestajOImunizaciji() {
        return new IzvestajOImunizaciji();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.RaspodelaDatihVakcinaPoProizvodjacima }
     * 
     */
    public IzvestajOImunizaciji.RaspodelaDatihVakcinaPoProizvodjacima createIzvestajOImunizacijiRaspodelaDatihVakcinaPoProizvodjacima() {
        return new IzvestajOImunizaciji.RaspodelaDatihVakcinaPoProizvodjacima();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.RaspodelaDatihVakcinaPoRednomBrojuDoze }
     * 
     */
    public IzvestajOImunizaciji.RaspodelaDatihVakcinaPoRednomBrojuDoze createIzvestajOImunizacijiRaspodelaDatihVakcinaPoRednomBrojuDoze() {
        return new IzvestajOImunizaciji.RaspodelaDatihVakcinaPoRednomBrojuDoze();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.MetaPodaci }
     * 
     */
    public IzvestajOImunizaciji.MetaPodaci createIzvestajOImunizacijiMetaPodaci() {
        return new IzvestajOImunizaciji.MetaPodaci();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.RaspodelaDatihVakcinaPoProizvodjacima.Proizvodjac }
     * 
     */
    public IzvestajOImunizaciji.RaspodelaDatihVakcinaPoProizvodjacima.Proizvodjac createIzvestajOImunizacijiRaspodelaDatihVakcinaPoProizvodjacimaProizvodjac() {
        return new IzvestajOImunizaciji.RaspodelaDatihVakcinaPoProizvodjacima.Proizvodjac();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.RaspodelaDatihVakcinaPoRednomBrojuDoze.Doza }
     * 
     */
    public IzvestajOImunizaciji.RaspodelaDatihVakcinaPoRednomBrojuDoze.Doza createIzvestajOImunizacijiRaspodelaDatihVakcinaPoRednomBrojuDozeDoza() {
        return new IzvestajOImunizaciji.RaspodelaDatihVakcinaPoRednomBrojuDoze.Doza();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.MetaPodaci.PeriodOd }
     * 
     */
    public IzvestajOImunizaciji.MetaPodaci.PeriodOd createIzvestajOImunizacijiMetaPodaciPeriodOd() {
        return new IzvestajOImunizaciji.MetaPodaci.PeriodOd();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.MetaPodaci.PeriodDo }
     * 
     */
    public IzvestajOImunizaciji.MetaPodaci.PeriodDo createIzvestajOImunizacijiMetaPodaciPeriodDo() {
        return new IzvestajOImunizaciji.MetaPodaci.PeriodDo();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.MetaPodaci.DatumIzdavanja }
     * 
     */
    public IzvestajOImunizaciji.MetaPodaci.DatumIzdavanja createIzvestajOImunizacijiMetaPodaciDatumIzdavanja() {
        return new IzvestajOImunizaciji.MetaPodaci.DatumIzdavanja();
    }

}
