//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.06 at 01:18:10 PM CET 
//


package com.immunization.backend.model.digitalni_sertifikat;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.immunization.backend.model.digitalni_sertifikat package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Qr_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "qr");
    private final static QName _ImePrezime_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "ime_prezime");
    private final static QName _Pol_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "pol");
    private final static QName _DatumRodjenja_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "datum_rodjenja");
    private final static QName _JMBG_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "JMBG");
    private final static QName _BrojPasosa_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "broj_pasosa");
    private final static QName _Tip_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "tip");
    private final static QName _ProizvodjacSerija_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "proizvodjac_serija");
    private final static QName _Datum_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "datum");
    private final static QName _ZdravstvenaUstanova_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "zdravstvena_ustanova");
    private final static QName _RTTest_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "RT_test");
    private final static QName _AgRDTTest_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "Ag_RDT_test");
    private final static QName _RBDSProteinTest_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "RBD_S_protein_test");
    private final static QName _Potpis_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "potpis");
    private final static QName _VrstaUzorka_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "vrsta_uzorka");
    private final static QName _Proizvodjac_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "proizvodjac");
    private final static QName _DatumVremeUzorkovanja_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "datum_vreme_uzorkovanja");
    private final static QName _DatumVremeIzdavanjaRezultata_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "datum_vreme_izdavanja_rezultata");
    private final static QName _Rezultat_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "rezultat");
    private final static QName _Laboratorija_QNAME = new QName("http://www.ftn.uns.ac.rs/digitalni-sertifikat", "laboratorija");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.immunization.backend.model.digitalni_sertifikat
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DigitalniSertifikat }
     * 
     */
    public DigitalniSertifikat createDigitalniSertifikat() {
        return new DigitalniSertifikat();
    }

    /**
     * Create an instance of {@link LicniPodaci }
     * 
     */
    public LicniPodaci createLicniPodaci() {
        return new LicniPodaci();
    }

    /**
     * Create an instance of {@link Vakcinacija }
     * 
     */
    public Vakcinacija createVakcinacija() {
        return new Vakcinacija();
    }

    /**
     * Create an instance of {@link Vakcina }
     * 
     */
    public Vakcina createVakcina() {
        return new Vakcina();
    }

    /**
     * Create an instance of {@link Testovi }
     * 
     */
    public Testovi createTestovi() {
        return new Testovi();
    }

    /**
     * Create an instance of {@link TTest }
     * 
     */
    public TTest createTTest() {
        return new TTest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "qr")
    public JAXBElement<String> createQr(String value) {
        return new JAXBElement<String>(_Qr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "ime_prezime")
    public JAXBElement<String> createImePrezime(String value) {
        return new JAXBElement<String>(_ImePrezime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "pol")
    public JAXBElement<String> createPol(String value) {
        return new JAXBElement<String>(_Pol_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "datum_rodjenja")
    public JAXBElement<XMLGregorianCalendar> createDatumRodjenja(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DatumRodjenja_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "JMBG")
    public JAXBElement<BigInteger> createJMBG(BigInteger value) {
        return new JAXBElement<BigInteger>(_JMBG_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "broj_pasosa")
    public JAXBElement<BigInteger> createBrojPasosa(BigInteger value) {
        return new JAXBElement<BigInteger>(_BrojPasosa_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "tip")
    public JAXBElement<String> createTip(String value) {
        return new JAXBElement<String>(_Tip_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "proizvodjac_serija")
    public JAXBElement<String> createProizvodjacSerija(String value) {
        return new JAXBElement<String>(_ProizvodjacSerija_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "datum")
    public JAXBElement<XMLGregorianCalendar> createDatum(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Datum_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "zdravstvena_ustanova")
    public JAXBElement<String> createZdravstvenaUstanova(String value) {
        return new JAXBElement<String>(_ZdravstvenaUstanova_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TTest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "RT_test")
    public JAXBElement<TTest> createRTTest(TTest value) {
        return new JAXBElement<TTest>(_RTTest_QNAME, TTest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TTest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "Ag_RDT_test")
    public JAXBElement<TTest> createAgRDTTest(TTest value) {
        return new JAXBElement<TTest>(_AgRDTTest_QNAME, TTest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TTest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "RBD_S_protein_test")
    public JAXBElement<TTest> createRBDSProteinTest(TTest value) {
        return new JAXBElement<TTest>(_RBDSProteinTest_QNAME, TTest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "potpis")
    public JAXBElement<byte[]> createPotpis(byte[] value) {
        return new JAXBElement<byte[]>(_Potpis_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "vrsta_uzorka")
    public JAXBElement<String> createVrstaUzorka(String value) {
        return new JAXBElement<String>(_VrstaUzorka_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "proizvodjac")
    public JAXBElement<String> createProizvodjac(String value) {
        return new JAXBElement<String>(_Proizvodjac_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "datum_vreme_uzorkovanja")
    public JAXBElement<String> createDatumVremeUzorkovanja(String value) {
        return new JAXBElement<String>(_DatumVremeUzorkovanja_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "datum_vreme_izdavanja_rezultata")
    public JAXBElement<String> createDatumVremeIzdavanjaRezultata(String value) {
        return new JAXBElement<String>(_DatumVremeIzdavanjaRezultata_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "rezultat")
    public JAXBElement<String> createRezultat(String value) {
        return new JAXBElement<String>(_Rezultat_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/digitalni-sertifikat", name = "laboratorija")
    public JAXBElement<String> createLaboratorija(String value) {
        return new JAXBElement<String>(_Laboratorija_QNAME, String.class, null, value);
    }

}
