//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.16 at 11:58:33 AM CET 
//


package com.immunization.common.model.zahtev_za_sertifikat;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.immunization.common.model.zahtev_za_sertifikat package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.immunization.common.model.zahtev_za_sertifikat
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZahtevZaSertifikat }
     * 
     */
    public ZahtevZaSertifikat createZahtevZaSertifikat() {
        return new ZahtevZaSertifikat();
    }

    /**
     * Create an instance of {@link ZahtevZaSertifikat.PodnosilacZahteva }
     * 
     */
    public ZahtevZaSertifikat.PodnosilacZahteva createZahtevZaSertifikatPodnosilacZahteva() {
        return new ZahtevZaSertifikat.PodnosilacZahteva();
    }

    /**
     * Create an instance of {@link ZahtevZaSertifikat.MetaPodaci }
     * 
     */
    public ZahtevZaSertifikat.MetaPodaci createZahtevZaSertifikatMetaPodaci() {
        return new ZahtevZaSertifikat.MetaPodaci();
    }

    /**
     * Create an instance of {@link ZahtevZaSertifikat.PodnosilacZahteva.RazlogZaPodnosenjeZahteva }
     * 
     */
    public ZahtevZaSertifikat.PodnosilacZahteva.RazlogZaPodnosenjeZahteva createZahtevZaSertifikatPodnosilacZahtevaRazlogZaPodnosenjeZahteva() {
        return new ZahtevZaSertifikat.PodnosilacZahteva.RazlogZaPodnosenjeZahteva();
    }

    /**
     * Create an instance of {@link ZahtevZaSertifikat.MetaPodaci.MestoIzdavanja }
     * 
     */
    public ZahtevZaSertifikat.MetaPodaci.MestoIzdavanja createZahtevZaSertifikatMetaPodaciMestoIzdavanja() {
        return new ZahtevZaSertifikat.MetaPodaci.MestoIzdavanja();
    }

    /**
     * Create an instance of {@link ZahtevZaSertifikat.MetaPodaci.DatumIzdavanja }
     * 
     */
    public ZahtevZaSertifikat.MetaPodaci.DatumIzdavanja createZahtevZaSertifikatMetaPodaciDatumIzdavanja() {
        return new ZahtevZaSertifikat.MetaPodaci.DatumIzdavanja();
    }

    /**
     * Create an instance of {@link ZahtevZaSertifikat.MetaPodaci.StatusZahteva }
     * 
     */
    public ZahtevZaSertifikat.MetaPodaci.StatusZahteva createZahtevZaSertifikatMetaPodaciStatusZahteva() {
        return new ZahtevZaSertifikat.MetaPodaci.StatusZahteva();
    }

}
