//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 08:23:02 PM CET 
//


package com.immunization.common.model.saglasnost;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.immunization.common.model.util.DatumRodjenja;
import com.immunization.common.model.util.MestoRodjenja;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="datum_rodjenja" type="{http://ftn.uns.ac.rs/util}datum_rodjenja"/&gt;
 *         &lt;element name="mesto_rodjenja" type="{http://ftn.uns.ac.rs/util}mesto_rodjenja"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datumRodjenja",
    "mestoRodjenja"
})
@XmlRootElement(name = "datum_i_mesto_rodjenja")
public class DatumIMestoRodjenja {

    @XmlElement(name = "datum_rodjenja", required = true)
    protected DatumRodjenja datumRodjenja;
    @XmlElement(name = "mesto_rodjenja", required = true)
    protected MestoRodjenja mestoRodjenja;

    /**
     * Gets the value of the datumRodjenja property.
     * 
     * @return
     *     possible object is
     *     {@link DatumRodjenja }
     *     
     */
    public DatumRodjenja getDatumRodjenja() {
        return datumRodjenja;
    }

    /**
     * Sets the value of the datumRodjenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatumRodjenja }
     *     
     */
    public void setDatumRodjenja(DatumRodjenja value) {
        this.datumRodjenja = value;
    }

    /**
     * Gets the value of the mestoRodjenja property.
     * 
     * @return
     *     possible object is
     *     {@link MestoRodjenja }
     *     
     */
    public MestoRodjenja getMestoRodjenja() {
        return mestoRodjenja;
    }

    /**
     * Sets the value of the mestoRodjenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link MestoRodjenja }
     *     
     */
    public void setMestoRodjenja(MestoRodjenja value) {
        this.mestoRodjenja = value;
    }

}
