//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 04:37:41 PM CET 
//


package com.immunization.common.model.saglasnost;

import javax.xml.bind.annotation.XmlAccessType;

import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pacijent_koristi_zastitu" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="naziv_sedista" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="opstina_sedista" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pacijentKoristiZastitu",
    "nazivSedista",
    "opstinaSedista"
})
@XmlRootElement(name = "ustanova_socijalne_zastite")
public class UstanovaSocijalneZastite {

    @XmlElement(name = "pacijent_koristi_zastitu")
    protected boolean pacijentKoristiZastitu;
    @XmlElement(name = "naziv_sedista", required = true)
    protected String nazivSedista;
    @XmlElement(name = "opstina_sedista", required = true)
    protected String opstinaSedista;

    /**
     * Gets the value of the pacijentKoristiZastitu property.
     * 
     */
    public boolean isPacijentKoristiZastitu() {
        return pacijentKoristiZastitu;
    }

    /**
     * Sets the value of the pacijentKoristiZastitu property.
     * 
     */
    public void setPacijentKoristiZastitu(boolean value) {
        this.pacijentKoristiZastitu = value;
    }

    /**
     * Gets the value of the nazivSedista property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivSedista() {
        return nazivSedista;
    }

    /**
     * Sets the value of the nazivSedista property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivSedista(String value) {
        this.nazivSedista = value;
    }

    /**
     * Gets the value of the opstinaSedista property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpstinaSedista() {
        return opstinaSedista;
    }

    /**
     * Sets the value of the opstinaSedista property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpstinaSedista(String value) {
        this.opstinaSedista = value;
    }

}
