//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.13 at 10:41:37 AM CET 
//


package com.immunization.common.model.interesovanje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.immunization.common.model.util.ImePrezime;
import com.immunization.common.model.util.Jmbg;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/interesovanje/}drzavljanstvo"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/interesovanje/}jmbg"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/interesovanje/}puno_ime"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/interesovanje/}kontakt_informacije"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/interesovanje/}dobrovoljni_davalac_krvi"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="about" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "drzavljanstvo",
    "jmbg",
    "punoIme",
    "kontaktInformacije",
    "dobrovoljniDavalacKrvi"
})
@XmlRootElement(name = "pacijent")
public class Pacijent {

    @XmlElement(required = true)
    protected Drzavljanstvo drzavljanstvo;
    @XmlElement(required = true)
    protected Jmbg jmbg;
    @XmlElement(name = "puno_ime", required = true)
    protected ImePrezime punoIme;
    @XmlElement(name = "kontakt_informacije", required = true)
    protected KontaktInformacije kontaktInformacije;
    @XmlElement(name = "dobrovoljni_davalac_krvi", required = true)
    protected DobrovoljniDavalacKrvi dobrovoljniDavalacKrvi;
    @XmlAttribute(name = "about", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String about;

    /**
     * Gets the value of the drzavljanstvo property.
     * 
     * @return
     *     possible object is
     *     {@link Drzavljanstvo }
     *     
     */
    public Drzavljanstvo getDrzavljanstvo() {
        return drzavljanstvo;
    }

    /**
     * Sets the value of the drzavljanstvo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Drzavljanstvo }
     *     
     */
    public void setDrzavljanstvo(Drzavljanstvo value) {
        this.drzavljanstvo = value;
    }

    /**
     * Gets the value of the jmbg property.
     * 
     * @return
     *     possible object is
     *     {@link Jmbg }
     *     
     */
    public Jmbg getJmbg() {
        return jmbg;
    }

    /**
     * Sets the value of the jmbg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Jmbg }
     *     
     */
    public void setJmbg(Jmbg value) {
        this.jmbg = value;
    }

    /**
     * Gets the value of the punoIme property.
     * 
     * @return
     *     possible object is
     *     {@link ImePrezime }
     *     
     */
    public ImePrezime getPunoIme() {
        return punoIme;
    }

    /**
     * Sets the value of the punoIme property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImePrezime }
     *     
     */
    public void setPunoIme(ImePrezime value) {
        this.punoIme = value;
    }

    /**
     * Gets the value of the kontaktInformacije property.
     * 
     * @return
     *     possible object is
     *     {@link KontaktInformacije }
     *     
     */
    public KontaktInformacije getKontaktInformacije() {
        return kontaktInformacije;
    }

    /**
     * Sets the value of the kontaktInformacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link KontaktInformacije }
     *     
     */
    public void setKontaktInformacije(KontaktInformacije value) {
        this.kontaktInformacije = value;
    }

    /**
     * Gets the value of the dobrovoljniDavalacKrvi property.
     * 
     * @return
     *     possible object is
     *     {@link DobrovoljniDavalacKrvi }
     *     
     */
    public DobrovoljniDavalacKrvi getDobrovoljniDavalacKrvi() {
        return dobrovoljniDavalacKrvi;
    }

    /**
     * Sets the value of the dobrovoljniDavalacKrvi property.
     * 
     * @param value
     *     allowed object is
     *     {@link DobrovoljniDavalacKrvi }
     *     
     */
    public void setDobrovoljniDavalacKrvi(DobrovoljniDavalacKrvi value) {
        this.dobrovoljniDavalacKrvi = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

}
