//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 11:03:10 AM CET 
//


package com.immunization.backend.model.interesovanje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/interesovanje/}pacijent"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/interesovanje/}zeljena_opstina_vakcinacije"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/interesovanje/}odabir_vakcina"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="datum" use="required" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="about" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pacijent",
    "zeljenaOpstinaVakcinacije",
    "odabirVakcina"
})
@XmlRootElement(name = "iskazivanje_interesovanja_za_vakcinaciju")
public class IskazivanjeInteresovanjaZaVakcinaciju {

    @XmlElement(required = true)
    protected Pacijent pacijent;
    @XmlElement(name = "zeljena_opstina_vakcinacije", required = true)
    protected String zeljenaOpstinaVakcinacije;
    @XmlElement(name = "odabir_vakcina", required = true)
    protected OdabirVakcina odabirVakcina;
    @XmlAttribute(name = "datum", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlAttribute(name = "about", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String about;

    /**
     * Gets the value of the pacijent property.
     * 
     * @return
     *     possible object is
     *     {@link Pacijent }
     *     
     */
    public Pacijent getPacijent() {
        return pacijent;
    }

    /**
     * Sets the value of the pacijent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pacijent }
     *     
     */
    public void setPacijent(Pacijent value) {
        this.pacijent = value;
    }

    /**
     * Gets the value of the zeljenaOpstinaVakcinacije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZeljenaOpstinaVakcinacije() {
        return zeljenaOpstinaVakcinacije;
    }

    /**
     * Sets the value of the zeljenaOpstinaVakcinacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZeljenaOpstinaVakcinacije(String value) {
        this.zeljenaOpstinaVakcinacije = value;
    }

    /**
     * Gets the value of the odabirVakcina property.
     * 
     * @return
     *     possible object is
     *     {@link OdabirVakcina }
     *     
     */
    public OdabirVakcina getOdabirVakcina() {
        return odabirVakcina;
    }

    /**
     * Sets the value of the odabirVakcina property.
     * 
     * @param value
     *     allowed object is
     *     {@link OdabirVakcina }
     *     
     */
    public void setOdabirVakcina(OdabirVakcina value) {
        this.odabirVakcina = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

}
