//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.06 at 01:18:10 PM CET 
//


package com.immunization.backend.model.interesovanje;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/interesovanje}drzavljanstvo"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/interesovanje}jmbg"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/interesovanje}puno_ime"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/interesovanje}kontakt_informacije"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/interesovanje}dobrovoljni_davalac_krvi"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "drzavljanstvo",
    "jmbg",
    "punoIme",
    "kontaktInformacije",
    "dobrovoljniDavalacKrvi"
})
@XmlRootElement(name = "pacijent")
public class Pacijent {

    @XmlElement(required = true)
    protected String drzavljanstvo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger jmbg;
    @XmlElement(name = "puno_ime", required = true)
    protected PunoIme punoIme;
    @XmlElement(name = "kontakt_informacije", required = true)
    protected KontaktInformacije kontaktInformacije;
    @XmlElement(name = "dobrovoljni_davalac_krvi")
    protected boolean dobrovoljniDavalacKrvi;

    /**
     * Gets the value of the drzavljanstvo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrzavljanstvo() {
        return drzavljanstvo;
    }

    /**
     * Sets the value of the drzavljanstvo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrzavljanstvo(String value) {
        this.drzavljanstvo = value;
    }

    /**
     * Gets the value of the jmbg property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getJmbg() {
        return jmbg;
    }

    /**
     * Sets the value of the jmbg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setJmbg(BigInteger value) {
        this.jmbg = value;
    }

    /**
     * Gets the value of the punoIme property.
     * 
     * @return
     *     possible object is
     *     {@link PunoIme }
     *     
     */
    public PunoIme getPunoIme() {
        return punoIme;
    }

    /**
     * Sets the value of the punoIme property.
     * 
     * @param value
     *     allowed object is
     *     {@link PunoIme }
     *     
     */
    public void setPunoIme(PunoIme value) {
        this.punoIme = value;
    }

    /**
     * Gets the value of the kontaktInformacije property.
     * 
     * @return
     *     possible object is
     *     {@link KontaktInformacije }
     *     
     */
    public KontaktInformacije getKontaktInformacije() {
        return kontaktInformacije;
    }

    /**
     * Sets the value of the kontaktInformacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link KontaktInformacije }
     *     
     */
    public void setKontaktInformacije(KontaktInformacije value) {
        this.kontaktInformacije = value;
    }

    /**
     * Gets the value of the dobrovoljniDavalacKrvi property.
     * 
     */
    public boolean isDobrovoljniDavalacKrvi() {
        return dobrovoljniDavalacKrvi;
    }

    /**
     * Sets the value of the dobrovoljniDavalacKrvi property.
     * 
     */
    public void setDobrovoljniDavalacKrvi(boolean value) {
        this.dobrovoljniDavalacKrvi = value;
    }

}
