//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 04:37:41 PM CET 
//


package com.immunization.backend.model.util;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.util package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.util
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ImePrezime }
     * 
     */
    public ImePrezime createImePrezime() {
        return new ImePrezime();
    }

    /**
     * Create an instance of {@link Pol }
     * 
     */
    public Pol createPol() {
        return new Pol();
    }

    /**
     * Create an instance of {@link DatumRodjenja }
     * 
     */
    public DatumRodjenja createDatumRodjenja() {
        return new DatumRodjenja();
    }

    /**
     * Create an instance of {@link Jmbg }
     * 
     */
    public Jmbg createJmbg() {
        return new Jmbg();
    }

    /**
     * Create an instance of {@link BrojPasosa }
     * 
     */
    public BrojPasosa createBrojPasosa() {
        return new BrojPasosa();
    }

    /**
     * Create an instance of {@link Ulica }
     * 
     */
    public Ulica createUlica() {
        return new Ulica();
    }

    /**
     * Create an instance of {@link Broj }
     * 
     */
    public Broj createBroj() {
        return new Broj();
    }

    /**
     * Create an instance of {@link Mesto }
     * 
     */
    public Mesto createMesto() {
        return new Mesto();
    }

    /**
     * Create an instance of {@link Opstina }
     * 
     */
    public Opstina createOpstina() {
        return new Opstina();
    }

    /**
     * Create an instance of {@link MestoRodjenja }
     * 
     */
    public MestoRodjenja createMestoRodjenja() {
        return new MestoRodjenja();
    }

    /**
     * Create an instance of {@link RadniStatus }
     * 
     */
    public RadniStatus createRadniStatus() {
        return new RadniStatus();
    }

}
