//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.06 at 01:18:10 PM CET 
//


package com.immunization.backend.model.util;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for radni_status.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="radni_status"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="zaposlen"/&gt;
 *     &lt;enumeration value="nezaposlen"/&gt;
 *     &lt;enumeration value="penzioner"/&gt;
 *     &lt;enumeration value="u\u010denik"/&gt;
 *     &lt;enumeration value="student"/&gt;
 *     &lt;enumeration value="dete"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "radni_status", namespace = "http://ftn.uns.ac.rs/util")
@XmlEnum
public enum RadniStatus {

    @XmlEnumValue("zaposlen")
    ZAPOSLEN("zaposlen"),
    @XmlEnumValue("nezaposlen")
    NEZAPOSLEN("nezaposlen"),
    @XmlEnumValue("penzioner")
    PENZIONER("penzioner"),
    @XmlEnumValue("u\u010denik")
    UCENIK("u\u010denik"),
    @XmlEnumValue("student")
    STUDENT("student"),
    @XmlEnumValue("dete")
    DETE("dete");
    private final String value;

    RadniStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RadniStatus fromValue(String v) {
        for (RadniStatus c: RadniStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
