//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 11:03:10 AM CET 
//


package com.immunization.backend.model.saglasnost;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import rs.ac.uns.ftn.util.BrojPasosa;
import rs.ac.uns.ftn.util.Jmbg;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="srpsko_drzavljanstvo"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="jmbg" type="{http://ftn.uns.ac.rs/util}jmbg"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="strano_drzavljanstvo"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="naziv_stranog_drzavljanstva" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="broj_pasosa_ili_ebs" type="{http://ftn.uns.ac.rs/util}broj_pasosa"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "srpskoDrzavljanstvo",
    "stranoDrzavljanstvo"
})
@XmlRootElement(name = "drzavljanstvo")
public class Drzavljanstvo {

    @XmlElement(name = "srpsko_drzavljanstvo")
    protected Drzavljanstvo.SrpskoDrzavljanstvo srpskoDrzavljanstvo;
    @XmlElement(name = "strano_drzavljanstvo")
    protected Drzavljanstvo.StranoDrzavljanstvo stranoDrzavljanstvo;

    /**
     * Gets the value of the srpskoDrzavljanstvo property.
     * 
     * @return
     *     possible object is
     *     {@link Drzavljanstvo.SrpskoDrzavljanstvo }
     *     
     */
    public Drzavljanstvo.SrpskoDrzavljanstvo getSrpskoDrzavljanstvo() {
        return srpskoDrzavljanstvo;
    }

    /**
     * Sets the value of the srpskoDrzavljanstvo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Drzavljanstvo.SrpskoDrzavljanstvo }
     *     
     */
    public void setSrpskoDrzavljanstvo(Drzavljanstvo.SrpskoDrzavljanstvo value) {
        this.srpskoDrzavljanstvo = value;
    }

    /**
     * Gets the value of the stranoDrzavljanstvo property.
     * 
     * @return
     *     possible object is
     *     {@link Drzavljanstvo.StranoDrzavljanstvo }
     *     
     */
    public Drzavljanstvo.StranoDrzavljanstvo getStranoDrzavljanstvo() {
        return stranoDrzavljanstvo;
    }

    /**
     * Sets the value of the stranoDrzavljanstvo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Drzavljanstvo.StranoDrzavljanstvo }
     *     
     */
    public void setStranoDrzavljanstvo(Drzavljanstvo.StranoDrzavljanstvo value) {
        this.stranoDrzavljanstvo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="jmbg" type="{http://ftn.uns.ac.rs/util}jmbg"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "jmbg"
    })
    public static class SrpskoDrzavljanstvo {

        @XmlElement(required = true)
        protected Jmbg jmbg;

        /**
         * Gets the value of the jmbg property.
         * 
         * @return
         *     possible object is
         *     {@link Jmbg }
         *     
         */
        public Jmbg getJmbg() {
            return jmbg;
        }

        /**
         * Sets the value of the jmbg property.
         * 
         * @param value
         *     allowed object is
         *     {@link Jmbg }
         *     
         */
        public void setJmbg(Jmbg value) {
            this.jmbg = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="naziv_stranog_drzavljanstva" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="broj_pasosa_ili_ebs" type="{http://ftn.uns.ac.rs/util}broj_pasosa"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nazivStranogDrzavljanstva",
        "brojPasosaIliEbs"
    })
    public static class StranoDrzavljanstvo {

        @XmlElement(name = "naziv_stranog_drzavljanstva", required = true)
        protected String nazivStranogDrzavljanstva;
        @XmlElement(name = "broj_pasosa_ili_ebs", required = true)
        protected BrojPasosa brojPasosaIliEbs;

        /**
         * Gets the value of the nazivStranogDrzavljanstva property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazivStranogDrzavljanstva() {
            return nazivStranogDrzavljanstva;
        }

        /**
         * Sets the value of the nazivStranogDrzavljanstva property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazivStranogDrzavljanstva(String value) {
            this.nazivStranogDrzavljanstva = value;
        }

        /**
         * Gets the value of the brojPasosaIliEbs property.
         * 
         * @return
         *     possible object is
         *     {@link BrojPasosa }
         *     
         */
        public BrojPasosa getBrojPasosaIliEbs() {
            return brojPasosaIliEbs;
        }

        /**
         * Sets the value of the brojPasosaIliEbs property.
         * 
         * @param value
         *     allowed object is
         *     {@link BrojPasosa }
         *     
         */
        public void setBrojPasosaIliEbs(BrojPasosa value) {
            this.brojPasosaIliEbs = value;
        }

    }

}
