//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 11:03:10 AM CET 
//


package com.immunization.backend.model.saglasnost;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/saglasnost}privremene_kontraindikacije"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/saglasnost}trajne_kontraindikacije"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "privremeneKontraindikacije",
    "trajneKontraindikacije"
})
@XmlRootElement(name = "kontraindikacija")
public class Kontraindikacija {

    @XmlElement(name = "privremene_kontraindikacije", required = true)
    protected PrivremeneKontraindikacije privremeneKontraindikacije;
    @XmlElement(name = "trajne_kontraindikacije", required = true)
    protected TrajneKontraindikacije trajneKontraindikacije;

    /**
     * Gets the value of the privremeneKontraindikacije property.
     * 
     * @return
     *     possible object is
     *     {@link PrivremeneKontraindikacije }
     *     
     */
    public PrivremeneKontraindikacije getPrivremeneKontraindikacije() {
        return privremeneKontraindikacije;
    }

    /**
     * Sets the value of the privremeneKontraindikacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrivremeneKontraindikacije }
     *     
     */
    public void setPrivremeneKontraindikacije(PrivremeneKontraindikacije value) {
        this.privremeneKontraindikacije = value;
    }

    /**
     * Gets the value of the trajneKontraindikacije property.
     * 
     * @return
     *     possible object is
     *     {@link TrajneKontraindikacije }
     *     
     */
    public TrajneKontraindikacije getTrajneKontraindikacije() {
        return trajneKontraindikacije;
    }

    /**
     * Sets the value of the trajneKontraindikacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrajneKontraindikacije }
     *     
     */
    public void setTrajneKontraindikacije(TrajneKontraindikacije value) {
        this.trajneKontraindikacije = value;
    }

}
