//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.06 at 01:18:10 PM CET 
//


package com.immunization.backend.model.saglasnost;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/saglasnost}informacije_o_pacijentu"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/saglasnost}evidencija_o_vakcinaciji"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="datum" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "informacijeOPacijentu",
    "evidencijaOVakcinaciji"
})
@XmlRootElement(name = "obrazac_saglasnosti_za_imunizaciju")
public class ObrazacSaglasnostiZaImunizaciju {

    @XmlElement(name = "informacije_o_pacijentu", required = true)
    protected InformacijeOPacijentu informacijeOPacijentu;
    @XmlElement(name = "evidencija_o_vakcinaciji", required = true)
    protected EvidencijaOVakcinaciji evidencijaOVakcinaciji;
    @XmlAttribute(name = "datum")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;

    /**
     * Gets the value of the informacijeOPacijentu property.
     * 
     * @return
     *     possible object is
     *     {@link InformacijeOPacijentu }
     *     
     */
    public InformacijeOPacijentu getInformacijeOPacijentu() {
        return informacijeOPacijentu;
    }

    /**
     * Sets the value of the informacijeOPacijentu property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformacijeOPacijentu }
     *     
     */
    public void setInformacijeOPacijentu(InformacijeOPacijentu value) {
        this.informacijeOPacijentu = value;
    }

    /**
     * Gets the value of the evidencijaOVakcinaciji property.
     * 
     * @return
     *     possible object is
     *     {@link EvidencijaOVakcinaciji }
     *     
     */
    public EvidencijaOVakcinaciji getEvidencijaOVakcinaciji() {
        return evidencijaOVakcinaciji;
    }

    /**
     * Sets the value of the evidencijaOVakcinaciji property.
     * 
     * @param value
     *     allowed object is
     *     {@link EvidencijaOVakcinaciji }
     *     
     */
    public void setEvidencijaOVakcinaciji(EvidencijaOVakcinaciji value) {
        this.evidencijaOVakcinaciji = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

}
