//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 04:37:41 PM CET 
//


package com.immunization.backend.model.saglasnost;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="naziv"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:vakcinisan_u" /&gt;
 *                 &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="vakcinacijski_punkt" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="informacije_o_lekaru"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="faksimil" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="broj_telefona" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "naziv",
    "vakcinacijskiPunkt",
    "informacijeOLekaru"
})
@XmlRootElement(name = "zdravstvena_ustanova")
public class ZdravstvenaUstanova {

    @XmlElement(required = true)
    protected ZdravstvenaUstanova.Naziv naziv;
    @XmlElement(name = "vakcinacijski_punkt", required = true)
    protected String vakcinacijskiPunkt;
    @XmlElement(name = "informacije_o_lekaru", required = true)
    protected ZdravstvenaUstanova.InformacijeOLekaru informacijeOLekaru;

    /**
     * Gets the value of the naziv property.
     * 
     * @return
     *     possible object is
     *     {@link ZdravstvenaUstanova.Naziv }
     *     
     */
    public ZdravstvenaUstanova.Naziv getNaziv() {
        return naziv;
    }

    /**
     * Sets the value of the naziv property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZdravstvenaUstanova.Naziv }
     *     
     */
    public void setNaziv(ZdravstvenaUstanova.Naziv value) {
        this.naziv = value;
    }

    /**
     * Gets the value of the vakcinacijskiPunkt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVakcinacijskiPunkt() {
        return vakcinacijskiPunkt;
    }

    /**
     * Sets the value of the vakcinacijskiPunkt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVakcinacijskiPunkt(String value) {
        this.vakcinacijskiPunkt = value;
    }

    /**
     * Gets the value of the informacijeOLekaru property.
     * 
     * @return
     *     possible object is
     *     {@link ZdravstvenaUstanova.InformacijeOLekaru }
     *     
     */
    public ZdravstvenaUstanova.InformacijeOLekaru getInformacijeOLekaru() {
        return informacijeOLekaru;
    }

    /**
     * Sets the value of the informacijeOLekaru property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZdravstvenaUstanova.InformacijeOLekaru }
     *     
     */
    public void setInformacijeOLekaru(ZdravstvenaUstanova.InformacijeOLekaru value) {
        this.informacijeOLekaru = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="faksimil" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="broj_telefona" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ime",
        "prezime",
        "faksimil",
        "brojTelefona"
    })
    public static class InformacijeOLekaru {

        @XmlElement(required = true)
        protected String ime;
        @XmlElement(required = true)
        protected String prezime;
        @XmlElement(required = true)
        protected String faksimil;
        @XmlElement(name = "broj_telefona", required = true)
        protected String brojTelefona;

        /**
         * Gets the value of the ime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIme() {
            return ime;
        }

        /**
         * Sets the value of the ime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIme(String value) {
            this.ime = value;
        }

        /**
         * Gets the value of the prezime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrezime() {
            return prezime;
        }

        /**
         * Sets the value of the prezime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrezime(String value) {
            this.prezime = value;
        }

        /**
         * Gets the value of the faksimil property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFaksimil() {
            return faksimil;
        }

        /**
         * Sets the value of the faksimil property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFaksimil(String value) {
            this.faksimil = value;
        }

        /**
         * Gets the value of the brojTelefona property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojTelefona() {
            return brojTelefona;
        }

        /**
         * Sets the value of the brojTelefona property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojTelefona(String value) {
            this.brojTelefona = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:vakcinisan_u" /&gt;
     *       &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xs:string" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Naziv {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "property", required = true)
        protected String property;
        @XmlAttribute(name = "datatype", required = true)
        protected String datatype;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            if (property == null) {
                return "pred:vakcinisan_u";
            } else {
                return property;
            }
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the datatype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatatype() {
            if (datatype == null) {
                return "xs:string";
            } else {
                return datatype;
            }
        }

        /**
         * Sets the value of the datatype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatatype(String value) {
            this.datatype = value;
        }

    }

}
