//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 08:23:02 PM CET 
//


package com.immunization.common.model.potvrda_o_vakcinaciji;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;

import com.immunization.common.model.util.DatumRodjenja;
import com.immunization.common.model.util.ImePrezime;
import com.immunization.common.model.util.Jmbg;
import com.immunization.common.model.util.Pol;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.immunization.common.model.potvrda_o_vakcinaciji package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SifraPotvrde_QNAME = new QName("http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", "sifra_potvrde");
    private final static QName _DatumIzdavanjaPotvrde_QNAME = new QName("http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", "datum_izdavanja_potvrde");
    private final static QName _QrKod_QNAME = new QName("http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", "qr_kod");
    private final static QName _ImePrezime_QNAME = new QName("http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", "ime_prezime");
    private final static QName _Pol_QNAME = new QName("http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", "pol");
    private final static QName _Jmbg_QNAME = new QName("http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", "jmbg");
    private final static QName _NazivVakcine_QNAME = new QName("http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", "naziv_vakcine");
    private final static QName _DatumDavanja_QNAME = new QName("http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", "datum_davanja");
    private final static QName _BrojSerije_QNAME = new QName("http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", "broj_serije");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.immunization.common.model.potvrda_o_vakcinaciji
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji }
     * 
     */
    public PotvrdaOVakcinaciji createPotvrdaOVakcinaciji() {
        return new PotvrdaOVakcinaciji();
    }

    /**
     * Create an instance of {@link LicniPodaci }
     * 
     */
    public LicniPodaci createLicniPodaci() {
        return new LicniPodaci();
    }

    /**
     * Create an instance of {@link Vakcinacije }
     * 
     */
    public Vakcinacije createVakcinacije() {
        return new Vakcinacije();
    }

    /**
     * Create an instance of {@link Vakcinacija }
     * 
     */
    public Vakcinacija createVakcinacija() {
        return new Vakcinacija();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", name = "sifra_potvrde")
    public JAXBElement<BigInteger> createSifraPotvrde(BigInteger value) {
        return new JAXBElement<BigInteger>(_SifraPotvrde_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", name = "datum_izdavanja_potvrde")
    public JAXBElement<XMLGregorianCalendar> createDatumIzdavanjaPotvrde(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DatumIzdavanjaPotvrde_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", name = "qr_kod")
    public JAXBElement<String> createQrKod(String value) {
        return new JAXBElement<String>(_QrKod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImePrezime }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ImePrezime }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", name = "ime_prezime")
    public JAXBElement<ImePrezime> createImePrezime(ImePrezime value) {
        return new JAXBElement<ImePrezime>(_ImePrezime_QNAME, ImePrezime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatumRodjenja }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DatumRodjenja }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", name = "datum_rodjenja")
    public JAXBElement<DatumRodjenja> createDatumRodjenja(DatumRodjenja value) {
        return new JAXBElement<DatumRodjenja>(_ImePrezime_QNAME, DatumRodjenja.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pol }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Pol }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", name = "pol")
    public JAXBElement<Pol> createPol(Pol value) {
        return new JAXBElement<Pol>(_Pol_QNAME, Pol.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Jmbg }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Jmbg }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", name = "jmbg")
    public JAXBElement<Jmbg> createJmbg(Jmbg value) {
        return new JAXBElement<Jmbg>(_Jmbg_QNAME, Jmbg.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", name = "naziv_vakcine")
    public JAXBElement<String> createNazivVakcine(String value) {
        return new JAXBElement<String>(_NazivVakcine_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", name = "datum_davanja")
    public JAXBElement<XMLGregorianCalendar> createDatumDavanja(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DatumDavanja_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji/", name = "broj_serije")
    public JAXBElement<BigInteger> createBrojSerije(BigInteger value) {
        return new JAXBElement<BigInteger>(_BrojSerije_QNAME, BigInteger.class, null, value);
    }

}
